[theme]
primaryColor = "#06074e"  # Deep red for buttons and highlights
backgroundColor = "#dce3f5"  # Soft pinkish-red for the main background
secondaryBackgroundColor = "#5a8bf1"  # Light red for secondary elements
textColor = "#172647"  # Dark maroon for strong contrast
font = "serif"  # Classic
