[theme]
primaryColor = "#e69ca7"              # Soft rose pink for buttons and highlights
backgroundColor = "#2e1f2b"           # Deep plum / mauve-black for background
secondaryBackgroundColor = "#3e2a35"  # Muted plum for cards and sidebars
textColor = "#fcefe9"                 # Soft cream-pink for readability
font = "serif"                        # Calm, nurturing serif font
