[theme]
primaryColor = "#B71C1C"  # Deep red for buttons and highlights
backgroundColor = "#FFEBEE"  # Soft pinkish-red for the main background
secondaryBackgroundColor = "#E57373"  # Light red for secondary elements
textColor = "#4A0000"  # Dark maroon for strong contrast
font = "serif"  # Classic
